### PR TITLE
fix: Add missing toString methods to TgpuResolvables

### LINKED ISSUE #738: Fix trace in resolution errors
Look for places where resolution error texts include, e.g., [object Object] instead of the field labels, and fix if possible.

### PR DESCRIPTION
**Pull request by mhawryluk**
closes #738

### CODE REVIEW

File: packages/typegpu/src/core/function/tgpuFn.ts [hunk 1]
```diff
@@ -259,4 +259,8 @@ class FnCall<Args extends AnyWgslData[], Return extends AnyWgslData | undefined>
       `${ctx.resolve(this._fn)}(${this._params.map((param) => ctx.resolve(param)).join(', ')})`,
     );
   }
+
+  toString() {
+    return `fn call: ${this.label ?? '<unnamed>'}`;
```
Comment (iwoplaza) [inline packages/typegpu/src/core/function/tgpuFn.ts]: Imo could be made a bit more inline with the rest of the labels.
```suggestion
    return `call:${this.label ?? '<unnamed>'}`;
```

File: packages/typegpu/src/core/pipeline/computePipeline.ts [hunk 2]
```diff
@@ -153,6 +153,8 @@ class ComputePipelineCore {
             });
             return '';
           },
+
+          toString: () => `compute pipeline code resolution: ${this._entryFn}`,
```
Comment (iwoplaza) [inline packages/typegpu/src/core/pipeline/computePipeline.ts]: The pipelines seem to house labels as well, we can use them here.
The used entry function will show up in the resolution stack trace anyway.
```suggestion
          toString: () => `computePipeline:${this.label ?? '<unnamed>'}`,
```

File: packages/typegpu/src/core/pipeline/renderPipeline.ts [hunk 3]
```diff
@@ -306,6 +306,9 @@ class RenderPipelineCore {
             });
             return '';
           },
+
+          toString: () =>
+            `render pipeline code resolution: ${vertexFn}, ${fragmentFn}`,
```
Comment (iwoplaza) [inline packages/typegpu/src/core/pipeline/renderPipeline.ts]: Same as above:
```suggestion
          toString: () => `renderPipeline:${this.label ?? '<unnamed>'}`,
```

File: packages/typegpu/src/core/texture/externalTexture.ts [hunk 4]
```diff
@@ -38,4 +38,8 @@ export class TgpuExternalTextureImpl implements TgpuExternalTexture {
 
     return id;
   }
+
+  toString() {
+    return `${this.resourceType}: ${this.label ?? '<unnamed>'}`;
```
Comment (iwoplaza) [inline packages/typegpu/src/core/texture/externalTexture.ts]: Removed the space to be more consistent with the rest.
```suggestion
    return `${this.resourceType}:${this.label ?? '<unnamed>'}`;
```

File: packages/typegpu/src/core/texture/texture.ts [hunk 5]
```diff
@@ -488,6 +488,10 @@ class TgpuFixedStorageTextureImpl
 
     return id;
   }
+
+  toString() {
+    return `${this.resourceType}: ${this.label ?? '<unnamed>'}`;
```
Comment (iwoplaza) [inline packages/typegpu/src/core/texture/texture.ts]:
```suggestion
    return `${this.resourceType}:${this.label ?? '<unnamed>'}`;
```

File: packages/typegpu/src/core/texture/texture.ts [hunk 6]
```diff
@@ -518,6 +522,10 @@ export class TgpuLaidOutStorageTextureImpl implements TgpuStorageTexture {
...
```
Comment (iwoplaza) [inline packages/typegpu/src/core/texture/texture.ts]:
```suggestion
    return `${this.resourceType}:${this.label ?? '<unnamed>'}`;
```

File: packages/typegpu/src/core/texture/texture.ts [hunk 7]
```diff
@@ -585,6 +593,10 @@ class TgpuFixedSampledTextureImpl
...
```
Comment (iwoplaza) [inline packages/typegpu/src/core/texture/texture.ts]:
```suggestion
    return `${this.resourceType}:${this.label ?? '<unnamed>'}`;
```

File: packages/typegpu/src/core/texture/texture.ts [hunk 8]
```diff
@@ -618,4 +630,8 @@ export class TgpuLaidOutSampledTextureImpl implements TgpuSampledTexture {
...
```
Comment (iwoplaza) [inline packages/typegpu/src/core/texture/texture.ts]:
```suggestion
    return `${this.resourceType}:${this.label ?? '<unnamed>'}`;
```

File: packages/typegpu/src/data/array.ts [hunk 9]
```diff
@@ -57,4 +57,8 @@ class TgpuArrayImpl<TElement extends AnyWgslData>
       throw new Error('Cannot nest runtime sized arrays.');
     }
   }
+
+  toString() {
+    return `array of ${this.elementType}`;
```
Comment (iwoplaza) [inline packages/typegpu/src/data/array.ts]:
```suggestion
    return `arrayOf(${this.elementType})`;
```

File: packages/typegpu/src/types.ts [hunk 10]
```diff
@@ -87,6 +87,7 @@ export interface ResolutionCtx {
 export interface TgpuResolvable {
   readonly label?: string | undefined;
   resolve(ctx: ResolutionCtx): string;
+  toString: () => string;
```
Comment (iwoplaza) [inline packages/typegpu/src/types.ts]:
```suggestion
  toString(): string;
```

**Review by iwoplaza — APPROVED** [review]
🐛🐛🐛
