### PR TITLE
Fix some tgpu-cli generator corner cases

### LINKED ISSUE #457: Generate proper code for runtime sized arrays
The following code:
```wgsl
@group(0) @binding(1) var<storage, read> matrices: array<mat4x4f>;
```
translates to:
```ts
export const layout0 = tgpu.bindGroupLayout({
  matrices: {
    storage: d.arrayOf(d.mat4x4f, arrayLength),
    access: 'readonly',
  },
}).$forceIndex(0);
```
I think it should be:
```diff lang=ts
export const layout0 = tgpu.bindGroupLayout({
  matrices: {
-   storage: d.arrayOf(d.mat4x4f, arrayLength),
+   storage: d.arrayOf(d.mat4x4f, 0),
    access: 'readonly',
  },
}).$forceIndex(0);
```
Or something like:
```diff lang=ts
+const RUNTIME_SIZED = 0;

export const layout0 = tgpu.bindGroupLayout({
  matrices: {
-   storage: d.arrayOf(d.mat4x4f, arrayLength),
+   storage: d.arrayOf(d.mat4x4f, RUNTIME_SIZED),
    access: 'readonly',
  },
}).$forceIndex(0);
```
to avoid potential confusion.

### LINKED ISSUE #464: Accept function that returns data in bind group layout entries.

### PR DESCRIPTION
**Pull request by mhawryluk**
closes #464 
closes #457 

* allow passing functions resolving to TgpuData to bindGroupLayouts entries for uniform and storage buffers, function is called with an argument of 0 automatically (see RuntimeSized)
* fix checking if referenced struct is already declared
* topologically sort struct definitions
* remove `.$forceIndex()` calls for now, as it is not yet implemented
* some code refactor

### CODE REVIEW

**Review by reczkok — APPROVED** [review]
Great work! 🎷

File: packages/typegpu/src/tgpuBindGroupLayout.ts [hunk 1]
```diff
@@ -211,11 +236,23 @@ const DEFAULT_READONLY_VISIBILITY: TgpuShaderStage[] = [
...
+  Entries extends Record<
+    string,
+    | TgpuLayoutEntry
+    | TgpuRuntimeSizedLayoutUniform
+    | TgpuRuntimeSizedLayoutStorage
+    | null
+  >,
+> = {
+  [K in keyof Entries]: Entries[K] extends TgpuRuntimeSizedLayoutUniform
+    ? TgpuLayoutUniform
```
Comment (iwoplaza) [inline packages/typegpu/src/tgpuBindGroupLayout.ts]: We are probably losing type information here. You can verify that by adding a test for the type of the bound entries. Maybe we can circumvent that if we do:

```suggestion
    ? Omit<Entries[K], 'uniform'> & { uniform: ReturnType<Entries[K]['uniform']> }
```

I would also experiment with merging the definition of TgpuLayoutUniform and TgpuRuntimeSizedLayoutUniform by just doing a union on:
```ts
uniform: AnyTgpuData | ((arrayLength: number) => AnyTgpuData);
```

**Review by iwoplaza — APPROVED** [review]
Awesome!! 🙌
