### PR TITLE
fix: `console.log` implicit pointers

### LINKED ISSUE #2393: fix: `console.log` and implicit pointers
```ts
const v = mutable.$;
console.log(v)
```
`v` will be a pointer, and `console.log` generation will fail.

### PR DESCRIPTION
**Pull request by aleksanderkatan**

### CODE REVIEW

File: packages/typegpu/src/tgsl/consoleLog/logGenerator.ts [hunk 1]
```diff
@@ -87,30 +88,41 @@ export class LogGeneratorImpl implements LogGenerator {
...
 
-    const nonStringArgs = concreteArgs.filter((e) => e.dataType !== UnknownData);
+    const concreteArgsWithStrings = args
+      .map((arg) =>
+        typeof arg.dataType === 'symbol'
+          ? arg
+          : convertToCommonType(ctx, [arg], [unptr(arg.dataType)])?.[0],
+      )
+      .filter((arg) => !!arg)
+      .map(concretizeSnippet);
```
[the remark this answers is not in the document]
Comment (aleksanderkatan) [reply packages/typegpu/src/tgsl/consoleLog/logGenerator.ts:106]: nah, this should never happen

File: packages/typegpu/src/tgsl/consoleLog/logGenerator.ts [hunk 2]
```diff
@@ -87,30 +89,46 @@ export class LogGeneratorImpl implements LogGenerator {
       return fallbackSnippet;
     }
 
-    const concreteArgs = concretizeSnippets(args);
     const id = this.#firstUnusedId++;
 
-    const nonStringArgs = concreteArgs.filter((e) => e.dataType !== UnknownData);
+    const concreteArgsWithStrings = args
+      .map((arg) => {
+        if (typeof arg.dataType === 'symbol') {
```
Comment (cieplypolar) [inline packages/typegpu/src/tgsl/consoleLog/logGenerator.ts]:
```suggestion
        if (arg.dataType === UnknownData) {
```

File: packages/typegpu/src/tgsl/consoleLog/logGenerator.ts [hunk 3]
```diff
@@ -87,30 +89,46 @@ export class LogGeneratorImpl implements LogGenerator {
...
+        const converted = convertToCommonType(ctx, [arg], [unptr(arg.dataType)])?.[0];
+        invariant(
+          converted,
+          `Internal error. Expected type ${arg.dataType} to be convertible to ${unptr(arg.dataType)}`,
+        );
+        return converted;
+      })
+      .map(concretizeSnippet);
+
+    const concreteArgs = concreteArgsWithStrings.filter((arg) => typeof arg.dataType !== 'symbol');
```
Comment (cieplypolar) [inline packages/typegpu/src/tgsl/consoleLog/logGenerator.ts]:
```suggestion
    const concreteArgs = concreteArgsWithStrings.filter((arg) => arg.dataType !== UnknownData);
```

**Review by cieplypolar — APPROVED** [review]
Good catch 💜 . Left some nits.

**Review by reczkok — APPROVED** [review]
Great fix
