### PR TITLE
fix: intermediate representation of array expression

### LINKED ISSUE #2017: fix: arrayExpr is resolved too early
Blocks #1965.

### PR DESCRIPTION
**Pull request by cieplypolar**
Before:
- Array expression was resolved immediately when the `NODE.arrayExpr` was encountered in the wgsl generator. Since the resulting snippet's value was a string, we couldn't really access array values.

Now:
- The `NODE.arrayExpr` returns an intermediate representation (`ArrayExpression`). Thereby, we delayed its resolution. 

Additional changes:
- separated logic for calling struct and array schemas in `NODE.call`
- moved validation if elements of array are references to `ArrayExpression`
- aligned cloning logic for arrays in `NODE.call`
- added/modified appropriate tests 

Closes #2017.

### CODE REVIEW

File: packages/typegpu/src/tgsl/wgslGenerator.ts [hunk 1]
```diff
@@ -527,7 +528,53 @@ ${this.ctx.pre}}`;
...
+          );
+        }
+
+        const arg = this.typedExpression(
+          argNodes[0],
+          callee.value,
+        );
+
+        // `d.arrayOf(...)([...])`.
+        // We resolve each element separately.
```
Comment (iwoplaza) [inline packages/typegpu/src/tgsl/wgslGenerator.ts]:
```suggestion
        // We don't resolve the ArrayExpression object itself to
        // avoid reference checks (we're copying so it's fine)
```

File: packages/typegpu/src/tgsl/generationHelpers.ts [hunk 2]
```diff
@@ -127,3 +138,47 @@ export function coerceToSnippet(value: unknown): Snippet {
 
   return snip(value, UnknownData, /* origin */ 'constant');
 }
+
+// defers the resolution of array expressions
```
Comment (reczkok) [inline packages/typegpu/src/tgsl/generationHelpers.ts]: Either JSDoc or remove IMO

File: packages/typegpu/src/tgsl/generationHelpers.ts [hunk 3]
```diff
@@ -127,3 +138,47 @@ export function coerceToSnippet(value: unknown): Snippet {
...
+export class ArrayExpression implements SelfResolvable {
+  readonly [$internal] = true;
+
+  constructor(
+    public readonly elementType: AnyWgslData,
+    public readonly type: AnyWgslData,
+    public readonly elements: Snippet[],
+  ) {
+  }
```
Comment (reczkok) [inline packages/typegpu/src/tgsl/generationHelpers.ts:158]:
```suggestion
  constructor(
    public readonly type: WgslArray<AnyWgslData>,
    public readonly elements: Snippet[],
  ) {}
```

File: packages/typegpu/src/tgsl/generationHelpers.ts [hunk 4]
```diff
@@ -127,3 +138,47 @@ export function coerceToSnippet(value: unknown): Snippet {
...
+        const snippetType =
+          ctx.resolve(concretize(elem.dataType as AnyData)).value;
+        throw new WgslTypeError(
+          `'${snippetStr}' reference cannot be used in an array constructor.\n-----\nTry '${snippetType}(${snippetStr})' or 'arrayOf(${snippetType}, count)([...])' to copy the value instead.\n-----`,
+        );
+      }
+    }
+
+    const arrayType = `array<${
+      ctx.resolve(this.elementType).value
```
Comment (reczkok) [inline packages/typegpu/src/tgsl/generationHelpers.ts]:
```suggestion
      ctx.resolve(this.type.elementType).value
```

File: packages/typegpu/src/tgsl/wgslGenerator.ts [hunk 5]
```diff
@@ -723,13 +755,18 @@ ${this.ctx.pre}}`;
...
+      const arrayType = arrayOf(
+        elemType as wgsl.AnyWgslData,
+        values.length,
+      );
 
       return snip(
-        stitch`${arrayType}(${values})`,
-        arrayOf(elemType as wgsl.AnyWgslData, values.length),
+        new ArrayExpression(
+          elemType as wgsl.AnyWgslData,
```
Comment (reczkok) [inline packages/typegpu/src/tgsl/wgslGenerator.ts]: This information is redundant since the arrayType contains it
```suggestion
```

File: packages/typegpu/tests/tgsl/wgslGenerator.test.ts [hunk 6]
```diff
@@ -522,6 +523,42 @@ describe('wgslGenerator', () => {
...
+        // deno-fmt-ignore: it's better that way
+        (
+          astInfo.ast?.body[1][0] as tinyest.Const
+        )[2] as unknown as tinyest.Expression,
+      );
+
+      expect(res.value instanceof ArrayExpression).toBe(true);
+      expect((res.value as unknown as ArrayExpression).type).toBe(res.dataType);
+    });
+  });
```
Comment (iwoplaza) [inline packages/typegpu/tests/tgsl/wgslGenerator.test.ts:540]: I really dislike this kind of tests as they're very fragile to changes in our internals. You can use `extractSnippetFromFn` instead (after making it public first), it returns the snippet of the last expression seen in the passed in 'use gpu' function.

Which means you can do:

```ts
const foo = () => {
  'use gpu';
  [d.u32(1), 2, 3]
};

const snippet = extractSnippetFromFn(foo);
expect(snippet.value instanceof ArrayExpression).toBe(true);
expect((snippet.value as ArrayExpression).type).toStrictEqual(d.arrayOf(d.u32, 3));
```

**Review by iwoplaza — APPROVED** [review]
A few small comments on the tests and docs, but otherwise great job! 💜
