### PR TITLE
Fixed bug in fluid sim and made the canvas not have a fixed size

### LINKED ISSUE #130: Fluid simulation drawing not working as intended.
On my machine the brush is off by half from the desired coordinates. @mhawryluk please check if you can reproduce the bug. ⚙︎

### PR DESCRIPTION
**Pull request by reczkok**
Closes #130 if the bug is reproducible.

### CODE REVIEW

File: apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics.ts [hunk 1]
```diff
@@ -536,8 +536,8 @@ canvas.onmousemove = (event) => {
   }
 
   const cellSize = canvas.width / options.size;
-  const x = Math.floor(event.offsetX / cellSize);
-  const y = options.size - Math.floor(event.offsetY / cellSize) - 1;
+  const x = Math.floor((event.offsetX * 2) / cellSize);
```
Comment (mhawryluk) [inline apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics.ts]:
```suggestion
  const x = Math.floor((event.offsetX * window.devicePixelRatio) / cellSize);
```

I think the bug appeared after changes in `Canvas.tsx` where we moved scaling canvas by `window.devicePixelRatio`. hardcoding `2` here fixes it only for the 100% zoom level, but there's still a noticable offset on different scales. replacing `2` with `window.devicePixelRatio` seems to fix the issue. same with y

Comment (reczkok) [reply apps/typegpu-docs/src/content/examples/simulation/fluid-with-atomics.ts]: Great - thanks!
