### PR TITLE
Fix overriding files in tgpu-cli with watch mode and --keep option

### LINKED ISSUE #471: Fix overriding files in `tgpu-cli` with watch mode and --keep option + better duplicate error handling
* with --keep option overwrite only newly created files,
* with --overwrite overwrite all

at the beginning of the program get a list of existing files, if no strategy provided end the program with a descriptive error. with --keep mode watch only new files, exclude existing from the watch list.

### PR DESCRIPTION
**Pull request by mhawryluk**
closes #471

### CODE REVIEW

File: packages/tgpu-cli/tgpu-cli.mjs [hunk 1]
```diff
@@ -123,12 +124,53 @@ Options:
...
+          ? []
+          : await Promise.all(
+              allMatchedFiles
+                .map((input) => ({ input, output: outputPathCompiler(input) }))
+                .map(
+                  async ({ input, output }) =>
+                    await access(output)
+                      .then(() => ({ input, output, outputExists: true }))
+                      .catch(() => ({ input, output, outputExists: false })),
+                ),
```
Comment (iwoplaza) [inline packages/tgpu-cli/tgpu-cli.mjs]: Tiny nit, this can be simplified a bit by returning the promise directly.

We could also return either an object, or null of we want to filter it out later.
```suggestion
                .map(
                  ({ input, output }) =>
                    access(output)
                      .then(() => ({ input, output }))
                      .catch(() => null),
                ),
```

File: packages/tgpu-cli/tgpu-cli.mjs [hunk 2]
```diff
@@ -123,12 +124,53 @@ Options:
...
+            ).then((existsResultsIO) =>
+              existsResultsIO.flatMap(({ input, output, outputExists }) =>
+                outputExists ? [{ input, output }] : [],
+              ),
+            );
```
Comment (iwoplaza) [inline packages/tgpu-cli/tgpu-cli.mjs]: Then we can just filter out the `null`s.
```suggestion
            ).then((existsResultsIO) =>
              existsResultsIO.filter((file): Exclude<typeof file, null> => !!file),
            );
```

**Review by iwoplaza — APPROVED** [review]
Great job! 🙌 💚
Left just a few nitpicks.
