### PR TITLE
fix: Remove redundant .with slot calls & chore: Cleanup ItemStateStack

### LINKED ISSUE #1854: impr: Optimize slot resolution
`resolutionCtx.ts`, the `withSlots` method.

After the patch from #1853, the slots are resolved correctly, but inefficiently (one by one, instead of all at once).

### PR DESCRIPTION
**Pull request by aleksanderkatan**
Changes:
- fix #1854,
- clean up stack layers code.

### CODE REVIEW

**Comment by aleksanderkatan** [comment]
I'm pretty sure I found a small bug in the resolution code. Take a look at these two snippets:

`resolutionCtx.ts`
```ts
  unwrap<T>(eventual: Eventual<T>): T {
    if (isProviding(eventual)) {
      return this.withSlots(
        eventual[$providing].pairs,
        () => this.unwrap(eventual[$providing].inner) as T,
      );
    }
```

`tgpuFn.ts`
```ts
    with(
      slot: TgpuSlot<unknown> | TgpuAccessor,
      value: unknown,
    ): TgpuFn<ImplSchema> {
      return createBoundFunction(fn, [
        ...pairs,
        [isAccessor(slot) ? slot.slot : slot, value],
      ]);
    },
```

I think that if we call `.with` multiple times, like:
```ts
    const getSize = tgpu.fn([], d.f32)`...`
      .$uses({ ... })
      .with(sizeSlot, 1)
      .with(colorSlot, RED)
      .with(shapeSlot, 2);
```

then `withSlots` is called with `[sizeSlot, colorSlot, shapeSlot]`, then with `[sizeSlot, colorSlot]`, then with `[sizeSlot]`.

File: packages/typegpu/src/resolutionCtx.ts [hunk 1]
```diff
@@ -141,11 +142,13 @@ class ItemStateStackImpl implements ItemStateStack {
...
       bindingMap: new WeakMap(pairs),
+      usedSet: new WeakSet(),
     });
   }
 
-  popSlotBindings() {
-    this.pop('slotBinding');
+  popSlotBindings(): WeakSet<TgpuSlot<unknown>> {
+    const slotBindings = this.pop('slotBinding') as SlotBindingLayer;
+    return slotBindings.usedSet;
```
Comment (reczkok) [inline packages/typegpu/src/resolutionCtx.ts]: We could do a little cleanup with the pop method since it can and should return a narrowed type:
```ts
type StackLayer =
  | ItemLayer
  | SlotBindingLayer
  | FunctionScopeLayer
  | BlockScopeLayer;

class ItemStateStackImpl implements ItemStateStack {
  private _stack: StackLayer[] = [];
  ...
  pop<T extends StackLayer['type']>(type: T): Extract<StackLayer, { type: T }>;
  pop(type?: StackLayer['type']): StackLayer | undefined;
  pop(type?: StackLayer['type']) {
    ...
  }
```
```suggestion
    return this.pop('slotBinding').usedSet;
```

**Review by reczkok — APPROVED** [review]
Great work!

File: packages/typegpu/src/resolutionCtx.ts (hunk 1 above)
Comment (aleksanderkatan) [reply packages/typegpu/src/resolutionCtx.ts]: I changed the type to the following:
```ts
pop<T extends StackLayer['type']>(type: T): Extract<StackLayer, { type: T }>;
pop(): StackLayer | undefined;
```
And I left the push methods unchanged. Let me know what you think

File: packages/typegpu/src/core/function/tgpuFn.ts [hunk 2]
```diff
@@ -290,7 +290,6 @@ function createBoundFunction<ImplSchema extends AnyFn>(
       value: unknown,
     ): TgpuFn<ImplSchema> {
       return createBoundFunction(fn, [
```
Comment (iwoplaza) [inline packages/typegpu/src/core/function/tgpuFn.ts]: I am wondering if passing in "innerFn" instead of "fn" and keeping the ... spread will lead to less wrapping (less layers to resolve)

Comment (aleksanderkatan) [reply packages/typegpu/src/core/function/tgpuFn.ts]: I thought it would break some things like toStrings, this is why I created another issue for that, but it turns out toStrings are broken right now:
```ts
  it('includes slot bindings in toString', () => {
    const firstSlot = tgpu.slot<number>();
    const secondSlot = tgpu.slot<number>();
    const thirdSlot = tgpu.slot<number>();

    const getSize = tgpu.fn([], d.f32)(() =>
      firstSlot.$ + secondSlot.$ + thirdSlot.$
    )
      .with(firstSlot, 1)
      .with(secondSlot, 2)
      .with(thirdSlot, 3);

    expect(getSize.toString()).toMatchInlineSnapshot(`"fn:getSize[thirdSlot=3]"`);
  });
```
And they work after the change:
```ts
  it('includes slot bindings in toString', () => {
    const firstSlot = tgpu.slot<number>();
    const secondSlot = tgpu.slot<number>();
    const thirdSlot = tgpu.slot<number>();

    const getSize = tgpu.fn([], d.f32)(() =>
      firstSlot.$ + secondSlot.$ + thirdSlot.$
    )
      .with(firstSlot, 1)
      .with(secondSlot, 2)
      .with(thirdSlot, 3);

    expect(getSize.toString()).toMatchInlineSnapshot(
      `"fn:getSize[firstSlot=1, secondSlot=2, thirdSlot=3]"`,
    );
  });
```
So yes, I guess I will go with that!

**Comment by iwoplaza** [comment]
I am unsure if I want unused slots to always be warned about. I can imagine a library that accepts a callback and provides it with a slot, and the callback can choose to use the slot or not at all. I am not yet sure how to both allow devs to have this introspection, and to not flood the console with false positives. Any thoughts?

**Review by iwoplaza — APPROVED** [review]
