### PR TITLE
fix: Perlin noise dynamic cache on Safari

### LINKED ISSUE #1356: fix: Perlin noise example not working on Safari

### PR DESCRIPTION
**Pull request by mhawryluk**
closes #1356

### CODE REVIEW

File: packages/typegpu-noise/src/perlin-3d/dynamic-cache.ts [hunk 1]
```diff
@@ -218,7 +218,8 @@ export function dynamicCacheConfig<Prefix extends string>(
           [`${prefix}memory` as const]: memoryBuffer,
         } as Bindings<Prefix>;
       },
-      set size(value: d.v3u) {
+      set size(_value: d.v3u) {
+        const value = d.vec4u(_value, 0); // temporary workaround because of vec4u uniform breaking on Safari
```
Comment (iwoplaza) [inline packages/typegpu-noise/src/perlin-3d/dynamic-cache.ts]:
```suggestion
        const value = d.vec4u(_value, 0); // temporary workaround because of vec3u uniform breaking on Safari
```

**Review by iwoplaza — APPROVED** [review]
Awesome! 👏 
Was this hard to debug on Safari? How did you manage to find the solution? 👀
