### PR TITLE
impr: Do not pack entry-point variables

### LINKED ISSUE #2301: bug: Packing all entry-point parameters causes uniformity checks to fail
The following snippet:
```wgsl
enable subgroups;
@group(0) @binding(0) var<storage, read_write> counter : u32;

struct ShaderInput {
 @builtin(subgroup_size) subgroupSize: u32,
 @builtin(global_invocation_id) globalInvocationId: vec3<u32>
};

@compute @workgroup_size(1)
fn main(input: ShaderInput) {
  for (var i = 0u; i < input.subgroupSize; i++) {
    counter += subgroupBroadcastFirst(counter) + i;
  }
}
```
Causes: 
```
Error while parsing WGSL: :13:16 error: 'subgroupBroadcastFirst' must only be called from subgroup uniform control flow
    counter += subgroupBroadcastFirst(counter) + i;
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

:12:3 note: control flow depends on possibly non-uniform value
  for (var i = 0u; i < input.subgroupSize; i++) {
  ^^^

:12:24 note: parameter 'input' of 'main' may be non-uniform
  for (var i = 0u; i < input.subgroupSize; i++) {
                       ^^^^^

 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor]).
```
While this is perfectly fine
```wgsl
enable subgroups;
@group(0) @binding(0) var<storage, read_write> counter : u32;

struct ShaderInput {
 @builtin(global_invocation_id) globalInvocationId: vec3<u32>
};

@compute @workgroup_size(1)
fn main(input: ShaderInput, @builtin(subgroup_size) subgroupSize: u32,) {
  for (var i = 0u; i < subgroupSize; i++) {
    counter += subgroupBroadcastFirst(counter) + i;
  }
}
```
We should rethink if packing all the parameters into a struct is a good idea after all (especially builtins). We could also easily remove unused parameters which could be useful for conditional feature usage.

### PR DESCRIPTION
**Pull request by reczkok**
closes #2301 
This pr replaces the default entry-point input/output variables to structs in favor of positional arguments - the only thing that remains inside a structs are inter-stage variables (sice we have to return a struct). This PR ***should*** not introduce any breaking changes for the end user, the API stays the same - only generated code changes. Generating shorter code should be an additional small win.
Also fixed some straight up invalid code in tests.
Also removes unused parameters which allows for some neat conditional feature usage without having to define two separate shells.

### CODE REVIEW

File: packages/typegpu/src/core/root/init.ts [hunk 1]
```diff
@@ -207,7 +207,11 @@ class WithBindingImpl implements WithBinding {
   createComputePipeline<ComputeIn extends Record<string, AnyComputeBuiltin>>(
     descriptor: TgpuComputePipeline.Descriptor<ComputeIn>,
   ): TgpuComputePipeline {
-    return INTERNAL_createComputePipeline(this._getRoot(), this._slotBindings, descriptor);
+    return INTERNAL_createComputePipeline(
+      this._getRoot(),
+      this._slotBindings,
+      descriptor as unknown as TgpuComputePipeline.Descriptor,
+    );
```
[the remark this answers is not in the document]
Comment (reczkok) [reply packages/typegpu/src/core/root/init.ts:217]: It's internal we're fine

File: packages/typegpu/src/core/function/tgpuComputeFn.ts [hunk 2]
```diff
@@ -78,19 +78,16 @@ export function computeFn<ComputeIn extends IORecord<AnyComputeBuiltin>>(options
...
+    argTypes: Object.values(options.in ?? {}) as ComputeIn[keyof ComputeIn][],
     returnType: Void,
-    workgroupSize: [
-      options.workgroupSize[0] ?? 1,
-      options.workgroupSize[1] ?? 1,
-      options.workgroupSize[2] ?? 1,
-    ],
+    workgroupSize: options.workgroupSize,
     entryPoint: 'compute',
   };
```
[the remark this answers is not in the document]
Comment (reczkok) [reply packages/typegpu/src/core/function/tgpuComputeFn.ts:85]: I hate that you are kinda right

File: packages/typegpu/src/core/function/entryInputRouter.ts [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+  declare readonly [$repr]: never;
+  readonly structArgName: string;
+  readonly dataSchema: BaseData | undefined;
+  /** Maps schemaKey → { WGSL arg name, type } */
+  readonly positionalArgsMap: Map<string, PositionalArgEntry>;
+
+  constructor(
+    structArgName: string,
+    dataSchema: BaseData | undefined,
+    positionalArgs: Array<{ schemaKey: string; argName: string; type: BaseData }>,
```
Comment (iwoplaza) [inline packages/typegpu/src/core/function/entryInputRouter.ts]: For consistency
```suggestion
    positionalArgs: { schemaKey: string; argName: string; type: BaseData }[],
```

File: packages/typegpu/src/resolutionCtx.ts [hunk 4]
```diff
@@ -444,50 +445,114 @@ export class ResolutionCtxImpl implements ResolutionCtx {
       this.#namespaceInternal.nameRegistry.pushFunctionScope();
       const args: Snippet[] = [];
       const argAliases: [string, Snippet][] = [];
+      // For entry functions: collect pending header entries to be filtered after body generation.
+      const pendingHeaderEntries: Array<{ argName: string; header: string }> = [];
```
Comment (iwoplaza) [inline packages/typegpu/src/resolutionCtx.ts]:
```suggestion
      const pendingHeaderEntries: { argName: string; header: string }[] = [];
```

File: packages/typegpu/tests/renderPipeline.test.ts
Comment (aleksanderkatan) [inline packages/typegpu/tests/renderPipeline.test.ts]: This test broke

```suggestion
      })`{ return vec4f(in.bar, 1); }`;
```

File: packages/typegpu/tests/tgsl/entryFnParamPruning.test.ts
Comment (aleksanderkatan) [inline packages/typegpu/tests/tgsl/entryFnParamPruning.test.ts:1]: Please add tests for wgsl-implemented entry points, and render pipelines

**Review by aleksanderkatan — COMMENTED** [review]
Looks good!

File: packages/typegpu/tests/tgsl/entryFnParamPruning.test.ts
Comment (iwoplaza) [reply packages/typegpu/tests/tgsl/entryFnParamPruning.test.ts:1]: WGSL-implemented functions don't prune unused params

Comment (aleksanderkatan) [reply packages/typegpu/tests/tgsl/entryFnParamPruning.test.ts:1]: Look at the other comment I made, that test has wgsl-implemented functions, did not use the `in`, and the entire struct was pruned, and it reappeared after `in` was used. Maybe this is not argument pruning per se, but it is new behavior introduced by this PR, and it isn't tested to my knowledge
