### PR TITLE
fix: Function call member access type inference

### LINKED ISSUE #1059: fix: Allow member access on FnCall return type and fix member access inference.

### PR DESCRIPTION
**Pull request by reczkok**
closes #1059

### CODE REVIEW

File: packages/typegpu/src/smol/wgslGenerator.ts [hunk 1]
```diff
@@ -195,6 +195,20 @@ export function generateExpression(
     // biome-ignore lint/suspicious/noExplicitAny: <sorry TypeScript>
     const propValue = (target.value as any)[property];
 
+    if (isWgsl(target.dataType)) {
```
Comment (iwoplaza) [inline packages/typegpu/src/smol/wgslGenerator.ts]:
```suggestion
    if (target.dataType !== UnknownData) {
```

**Review by iwoplaza — CHANGES_REQUESTED** [review]

File: packages/typegpu/src/data/matrix.ts [hunk 2]
```diff
@@ -52,7 +53,7 @@ function createMatSchema<
     '~repr': undefined as unknown as ValueType,
     type: options.type,
     label: options.type,
-  };
+  } as unknown as AnyWgslData;
```
[the remark this answers is not in the document]
Comment (iwoplaza) [reply packages/typegpu/src/data/matrix.ts:57]: These are library internals, so type casting is useful here.

File: packages/typegpu/src/smol/wgslGenerator.ts [hunk 3]
```diff
@@ -273,9 +291,14 @@ export function generateExpression(
...
     // Assuming that `id` is callable
-    return (idValue as unknown as (...args: unknown[]) => unknown)(
+    const fnRes = (idValue as unknown as (...args: unknown[]) => unknown)(
       ...resolvedResources,
     ) as Resource;
+
+    return {
+      value: resolveRes(ctx, fnRes),
+      dataType: fnRes.dataType,
+    };
```
Comment (iwoplaza) [inline packages/typegpu/src/smol/wgslGenerator.ts:327]: Let's not resolve the fn call here, in case it's not a TGPU function we're calling. We can branch here to see if we're calling a TGPU fn, and if not, we throw an error.

The only JS functions we want to allow are our Dual Impl functions. Could we mark them with `[$internal]: {}` props to see if they originate from us?

**Review by iwoplaza — CHANGES_REQUESTED** [review]

File: packages/typegpu/src/smol/wgslGenerator.ts [hunk 4]
```diff
@@ -189,16 +190,32 @@ export function generateExpression(
     if (typeof target.value === 'string') {
       return {
         value: `${target.value}.${property}`,
-        dataType: getTypeForPropAccess(target.dataType as Wgsl, property),
+        dataType: isWgsl(target.dataType)
```
Comment (iwoplaza) [inline packages/typegpu/src/smol/wgslGenerator.ts]: Since `LooseData` don't fall under the umbrella of Wgsl, we don't get type inference for them here. We can use `isData` instead to both reduce the amount of unnecessary checks, and to increase the scope.
```suggestion
        dataType: isData(target.dataType)
```

File: packages/typegpu/src/smol/wgslGenerator.ts [hunk 5]
```diff
@@ -189,16 +190,32 @@ export function generateExpression(
...
+          ? getTypeForPropAccess(target.dataType, property)
+          : UnknownData,
       };
     }
     // biome-ignore lint/suspicious/noExplicitAny: <sorry TypeScript>
     const propValue = (target.value as any)[property];
 
+    if (target.dataType.type !== 'unknown') {
+      if (target.dataType.type.startsWith('mat') && property === 'columns') {
```
Comment (iwoplaza) [inline packages/typegpu/src/smol/wgslGenerator.ts]: Could we create an `isMatSchema` function for this? Will be easier to refactor once we transition to symbols.

File: packages/typegpu/src/smol/wgslGenerator.ts [hunk 6]
```diff
@@ -226,7 +243,9 @@ export function generateExpression(
 
     return {
       value: `${targetStr}[${propertyStr}]`,
-      dataType: getTypeForIndexAccess(targetExpr.dataType as d.AnyWgslData),
+      dataType: isWgsl(targetExpr.dataType)
```
Comment (iwoplaza) [inline packages/typegpu/src/smol/wgslGenerator.ts]:
```suggestion
      dataType: isData(targetExpr.dataType)
```

File: packages/typegpu/src/smol/wgslGenerator.ts [hunk 7]
```diff
@@ -273,9 +292,18 @@ export function generateExpression(
...
 
     // Assuming that `id` is callable
-    return (idValue as unknown as (...args: unknown[]) => unknown)(
+    const fnRes = (idValue as unknown as (...args: unknown[]) => unknown)(
       ...resolvedResources,
     ) as Resource;
+
+    if (!isMarkedInternal(idValue)) {
+      throw new Error(`Function ${String(idValue)} is not marked as internal.`);
+    }
```
Comment (iwoplaza) [inline packages/typegpu/src/smol/wgslGenerator.ts]: Also, I feel like we should check this earlier, before calling the function.

```suggestion
    if (!isMarkedInternal(idValue)) {
      throw new Error(`Function ${String(idValue)} has not been created using TypeGPU APIs. Did you mean to wrap the function with tgpu.fn(args, return)(...) ?`);
    }
```

File: packages/typegpu/src/smol/wgslGenerator.ts (hunk 3 above)
Comment (iwoplaza) [reply packages/typegpu/src/smol/wgslGenerator.ts:327]: Still yet to be addressed 👀

File: packages/typegpu/src/types.ts [hunk 8]
```diff
@@ -234,3 +228,13 @@ export function hasInternalDataType(
...
 }
+
+export function isMarkedInternal(
+  value: unknown,
+): value is { [$internal]: Record<string, unknown> } {
+  return (
+    !!value &&
+    (typeof value === 'object' || typeof value === 'function') &&
+    $internal in (value as object)
+  );
```
Comment (iwoplaza) [inline packages/typegpu/src/types.ts]: I believe this should be enough 👍
```suggestion
  return !!(value as { [$internal]: Record<string, unknown> })?.[$internal];
```

**Review by iwoplaza — CHANGES_REQUESTED** [review]

File: packages/typegpu/src/smol/wgslGenerator.ts (hunk 3 above)
Comment (reczkok) [reply packages/typegpu/src/smol/wgslGenerator.ts:327]: But how exactly do you want to handle this? We didn't want to resolve in case it's not a Tgpu function. Do we not want to resolve at all? What about FnCall

Comment (reczkok) [reply packages/typegpu/src/smol/wgslGenerator.ts:327]: Do we want to check for `FnCall` specifically or change the index/member access logic?

File: packages/typegpu/src/types.ts (hunk 8 above)
Comment (reczkok) [reply packages/typegpu/src/types.ts]: Not for TS
```ts
// biome-ignore lint/suspicious/noExplicitAny: <they told me to>
return !!(value as any)?.[$internal];
```
or
```ts
return !!(
  value as {
    [$internal]: Record<string, unknown>;
  }
)?.[$internal];
```

File: packages/typegpu/src/smol/wgslGenerator.ts (hunk 3 above)
Comment (iwoplaza) [reply packages/typegpu/src/smol/wgslGenerator.ts:327]: Oh wait... right, we disabled non-tgpu functions, so objects returned from functions will always be resolvable. Let's keep it as it is for now, until we want to implement compile-time functions.

File: packages/typegpu/src/types.ts (hunk 8 above)
Comment (iwoplaza) [reply packages/typegpu/src/types.ts]: Right! Updated my suggestion 🙌. (should be a one-liner, biome does not fold it for me)

**Review by iwoplaza — APPROVED** [review]
Let's gooo 🎉
