### PR TITLE
fix: concretize abstract types when performing division

### LINKED ISSUE #1551: impr: Add concretisation to `convertToCommonType`
Case:
```ts
const buf = root.createBuffer(d.arrayOf(d.f32, 1)).$usage('storage');
const val = buf.as('mutable');

const f = tgpu['~unstable'].computeFn({
  in: { gid: d.builtin.globalInvocationId },
  workgroupSize: [1],
})((input) => {
  val.$[0] = 1 / 5;
});

const p = root['~unstable'].withCompute(f).createPipeline();

p.dispatchWorkgroups(1);

const x = await buf.read();
console.log('Div on gpu: ', x);
console.log('Div in js: ', 1 / 5);
```
We pass `1 / 5` to `convertToCommonType` with forced type of `f32 | f16` but since both `1` and `5` are abstract we decide to do nothing. This breaks because WGSL treats `1` and `5` as abstract integers and reduces the division to `0`. We want to add a flag to `convertToCommonType` that forces concretisation of abstract types before the proper conversion.
After we call `concretise` on `1` nad `5` our conversion system will treat them as `i32` and cast to `f32` properly.

### PR DESCRIPTION
**Pull request by cieplypolar**
Changes:
- `convertToCommonType` now has an additional parameter, `concretizeTypes`, which makes the function concretize the types before looking for the best conversion
- `generateExpression` now concretizes types when it encounters division
- tests have been updated accordingly

Closes #1551.

### CODE REVIEW

File: packages/typegpu/src/tgsl/generationHelpers.ts [hunk 1]
```diff
@@ -517,18 +518,36 @@ function applyActionToSnippet(
   }
 }
 
-export function convertToCommonType(
-  ctx: GenerationCtx,
-  values: Snippet[],
-  restrictTo?: AnyData[],
+export type ConvertToCommonTypeInfo = {
```
Comment (iwoplaza) [inline packages/typegpu/src/tgsl/generationHelpers.ts]: Tiny nitpick, we commonly use the `Options` suffix for the named function parameters type
```suggestion
export type ConvertToCommonTypeOptions = {
```

File: packages/typegpu/src/tgsl/generationHelpers.ts [hunk 2]
```diff
@@ -517,18 +518,36 @@ function applyActionToSnippet(
...
 
+  if (concretizeTypes) {
+    types = types.map((type) => {
+      if (isWgslData(type)) {
+        return concretize(type);
+      }
+      return type;
+    });
+  }
+
```
Comment (reczkok) [inline packages/typegpu/src/tgsl/generationHelpers.ts]: Since we know concretize is an identity function for non-abstract types (the only prerequisite is that the input has a `type` field) we can simplify this a little.
```suggestion
  const types = values.map((value) =>
    concretizeTypes ? concretize(value.dataType as AnyData) : value.dataType
  );

  if (types.some((type) => type === UnknownData)) {
    return undefined;
  }

```

Comment (cieplypolar) [reply packages/typegpu/src/tgsl/generationHelpers.ts]: I have to cast `value.dataType` to `AnyWgslData`, but we are fine, since `AnyData` will fall to identity.
